### ISSUE TITLE
Got wrong value in config

### ISSUE THREAD

**Issue by LSDog** [CSWesley/Knockback#1]
maybe you get the wrong value in line 33

**Comment by CSWesley** [comment]
> maybe you get the wrong value in line 33

could you explain more?

**Comment by LSDog** [comment]
In Knockback.java, line 33
![IMG_20210422_225608](https://user-images.githubusercontent.com/61925478/115736926-444ddf80-a3be-11eb-839d-2436e8bb38fa.jpg)
you get the wrong value for player's knockback, it should be "knockback-of-players".

**Comment by CSWesley** [comment]
> In Knockback.java, line 33
> ![IMG_20210422_225608](https://user-images.githubusercontent.com/61925478/115736926-444ddf80-a3be-11eb-839d-2436e8bb38fa.jpg)
> you get the wrong value for player's knockback, it should be "knockback-of-players".

Thank you SO MUCH! I didn't even see that! :D

**Comment by LSDog** [comment]
😉👌
